### ISSUE TITLE
El calendario no se imprime

### ISSUE THREAD

**Issue by anton01** [btactic/zimbra-catala#2]
Cuando intento imprimir el calendario la hoja de impresión sale en blanco.

En el mailbox log se puede ver el siguiente error:
`
2016-02-11 16:41:27,395 WARN  [qtp509886383-23555:https://172.22.1.80:8443/h/printcalendar?l=10,405&origView=workWeek&view=week&date=20160207T000000&endDate=20160213T235959&ft=09:00&tt=14:00&wd=true&ow=false&od=false&imc=false&wdays=1,2,3,4,5&tz=Europe/Berlin&skin=harmony] [] webclient - Unterminated quote
java.lang.IllegalArgumentException: Unterminated quote
        at java.text.SimpleDateFormat.compile(SimpleDateFormat.java:842)
        at java.text.SimpleDateFormat.initialize(SimpleDateFormat.java:634)
        at java.text.SimpleDateFormat.<init>(SimpleDateFormat.java:605)
        at com.zimbra.cs.taglib.tag.i18n.FormatDateTag.doTag(FormatDateTag.java:91)
        at org.apache.jsp.tag.web.calendar.multiDay_tag._jspx_meth_fmt_formatDate_9(org.apache.jsp.tag.web.calendar.multiDay_tag:4511)
        at org.apache.jsp.tag.web.calendar.multiDay_tag.doTag(org.apache.jsp.tag.web.calendar.multiDay_tag:875)
        at org.apache.jsp.tag.web.calendar.multiDayPrintView_tag._jspx_meth_app_multiDay_0(org.apache.jsp.tag.web.calendar.multiDayPrintView_tag:335)
        at org.apache.jsp.tag.web.calendar.multiDayPrintView_tag._jspx_meth_c_set_1(org.apache.jsp.tag.web.calendar.multiDayPrintView_tag:300)
        at org.apache.jsp.tag.web.calendar.multiDayPrintView_tag.access$4(org.apache.jsp.tag.web.calendar.multiDayPrintView_tag:284)
        at org.apache.jsp.tag.web.calendar.multiDayPrintView_tag$multiDayPrintView_tagHelper.invoke0(org.apache.jsp.tag.web.calendar.multiDayPrintView_tag:439)
        at org.apache.jsp.tag.web.calendar.multiDayPrintView_tag$multiDayPrintView_tagHelper.invoke(org.apache.jsp.tag.web.calendar.multiDayPrintView_tag:455)
        at org.apache.jsp.tag.web.infra.handleError_tag._jspx_meth_c_catch_0(org.apache.jsp.tag.web.infra.handleError_tag:222)
        at org.apache.jsp.tag.web.infra.handleError_tag.doTag(org.apache.jsp.tag.web.infra.handleError_tag:86)
        at org.apache.jsp.tag.web.calendar.multiDayPrintView_tag.doTag(org.apache.jsp.tag.web.calendar.multiDayPrintView_tag:198)
        at org.apache.jsp.h.printcalendar._jspx_meth_app_multiDayPrintView_2(org.apache.jsp.h.printcalendar:1198)
        at org.apache.jsp.h.printcalendar._jspx_meth_c_when_5(org.apache.jsp.h.printcalendar:1166)
        at org.apache.jsp.h.printcalendar._jspx_meth_c_choose_3(org.apache.jsp.h.printcalendar:1039)
        at org.apache.jsp.h.printcalendar.access$14(org.apache.jsp.h.printcalendar:1024)
        at org.apache.jsp.h.printcalendar$printcalendarHelper.invoke1(org.apache.jsp.h.printcalendar:1387)
        at org.apache.jsp.h.printcalendar$printcalendarHelper.invoke(org.apache.jsp.h.printcalendar:1406)
        at org.apache.jsp.tag.web.infra.handleError_tag._jspx_meth_c_catch_0(org.apache.jsp.tag.web.infra.handleError_tag:222)
        at org.apache.jsp.tag.web.infra.handleError_tag.doTag(org.apache.jsp.tag.web.infra.handleError_tag:86)
        at org.apache.jsp.h.printcalendar._jspx_meth_app_handleError_1(org.apache.jsp.h.printcalendar:1020)
        at org.apache.jsp.h.printcalendar._jspService(org.apache.jsp.h.printcalendar:175)
        at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:111)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
        at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:411)
        at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:473)
        at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:377)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
        at com.zimbra.webClient.servlet.JspServlet.service(JspServlet.java:58)
        at org.eclipse.jetty.servlet.JspPropertyGroupServlet.service(JspPropertyGroupServlet.java:139)
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:738)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1651)
        at com.zimbra.cs.servlet.RequestStringFilter.doFilter(RequestStringFilter.java:54)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1622)
        at com.zimbra.webClient.filters.RestFilter.doFilter(RestFilter.java:46)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1622)
        at com.zimbra.webClient.filters.ForwardFilter.doFilter(ForwardFilter.java:88)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1622)
        at com.zimbra.cs.servlet.SetHeaderFilter.doFilter(SetHeaderFilter.java:59)
        at com.zimbra.webClient.filters.SetHeaderFilter.doFilter(SetHeaderFilter.java:248)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1622)
        at org.eclipse.jetty.servlets.UserAgentFilter.doFilter(UserAgentFilter.java:83)
        at org.eclipse.jetty.servlets.GzipFilter.doFilter(GzipFilter.java:351)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1622)
        at com.zimbra.cs.servlet.ContextPathBasedThreadPoolBalancerFilter.doFilter(ContextPathBasedThreadPoolBalancerFilter.java:107)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1622)
        at com.zimbra.cs.servlet.ZimbraQoSFilter.doFilter(ZimbraQoSFilter.java:116)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1622)
        at org.eclipse.jetty.servlets.DoSFilter.doFilterChain(DoSFilter.java:457)
        at org.eclipse.jetty.servlets.DoSFilter.doFilter(DoSFilter.java:326)
        at org.eclipse.jetty.servlets.DoSFilter.doFilter(DoSFilter.java:299)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1622)
        at com.zimbra.webClient.filters.CharEncodingFilter.doFilter(CharEncodingFilter.java:37)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1622)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:549)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
        at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:544)
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:221)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1111)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:478)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:183)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1045)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
        at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:199)
        at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:109)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
        at org.eclipse.jetty.rewrite.handler.RewriteHandler.handle(RewriteHandler.java:309)
        at org.eclipse.jetty.server.handler.DebugHandler.handle(DebugHandler.java:81)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
        at org.eclipse.jetty.server.Server.handle(Server.java:462)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:279)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:232)
        at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:534)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:607)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:536)
        at java.lang.Thread.run(Thread.java:745)
2016-02-11 16:41:27,396 WARN  [qtp509886383-23555:https://172.22.1.80:8443/h/printcalendar?l=10,405&origView=workWeek&view=week&date=20160207T000000&endDate=20160213T235959&ft=09:00&tt=14:00&wd=true&ow=false&od=false&imc=false&wdays=1,2,3,4,5&tz=Europe/Berlin&skin=harmony] [] webclient - local exception
com.zimbra.cs.taglib.bean.ZTagLibException: Unterminated quote
ExceptionId:qtp509886383-23555:https://172.22.1.80:8443/h/printcalendar?l=10,405&origView=workWeek&view=week&date=20160207T000000&endDate=20160213T235959&ft=09:00&tt=14:00&wd=true&ow=false&od=false&imc=false&wdays=1,2,3,4,5&tz=Europe/Berlin&skin=harmony:1455205287396:fe27ac870279f807
Code:ztaglib.TAG_EXCEPTION
        at com.zimbra.cs.taglib.bean.ZTagLibException.TAG_EXCEPTION(ZTagLibException.java:60)
        at com.zimbra.cs.taglib.bean.ZExceptionBean.<init>(ZExceptionBean.java:81)
        at com.zimbra.cs.taglib.tag.GetExceptionTag.doTag(GetExceptionTag.java:42)
        at org.apache.jsp.tag.web.infra.handleError_tag.doTag(org.apache.jsp.tag.web.infra.handleError_tag:102)
        at org.apache.jsp.tag.web.calendar.multiDayPrintView_tag.doTag(org.apache.jsp.tag.web.calendar.multiDayPrintView_tag:198)
        at org.apache.jsp.h.printcalendar._jspx_meth_app_multiDayPrintView_2(org.apache.jsp.h.printcalendar:1198)
        at org.apache.jsp.h.printcalendar._jspx_meth_c_when_5(org.apache.jsp.h.printcalendar:1166)
        at org.apache.jsp.h.printcalendar._jspx_meth_c_choose_3(org.apache.jsp.h.printcalendar:1039)
        at org.apache.jsp.h.printcalendar.access$14(org.apache.jsp.h.printcalendar:1024)
        at org.apache.jsp.h.printcalendar$printcalendarHelper.invoke1(org.apache.jsp.h.printcalendar:1387)
        at org.apache.jsp.h.printcalendar$printcalendarHelper.invoke(org.apache.jsp.h.printcalendar:1406)
        at org.apache.jsp.tag.web.infra.handleError_tag._jspx_meth_c_catch_0(org.apache.jsp.tag.web.infra.handleError_tag:222)
        at org.apache.jsp.tag.web.infra.handleError_tag.doTag(org.apache.jsp.tag.web.infra.handleError_tag:86)
        at org.apache.jsp.h.printcalendar._jspx_meth_app_handleError_1(org.apache.jsp.h.printcalendar:1020)
        at org.apache.jsp.h.printcalendar._jspService(org.apache.jsp.h.printcalendar:175)
        at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:111)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
        at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:411)
        at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:473)
        at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:377)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
        at com.zimbra.webClient.servlet.JspServlet.service(JspServlet.java:58)
        at org.eclipse.jetty.servlet.JspPropertyGroupServlet.service(JspPropertyGroupServlet.java:139)
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:738)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1651)
        at com.zimbra.cs.servlet.RequestStringFilter.doFilter(RequestStringFilter.java:54)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1622)
        at com.zimbra.webClient.filters.RestFilter.doFilter(RestFilter.java:46)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1622)
        at com.zimbra.webClient.filters.ForwardFilter.doFilter(ForwardFilter.java:88)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1622)
        at com.zimbra.cs.servlet.SetHeaderFilter.doFilter(SetHeaderFilter.java:59)
        at com.zimbra.webClient.filters.SetHeaderFilter.doFilter(SetHeaderFilter.java:248)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1622)
        at org.eclipse.jetty.servlets.UserAgentFilter.doFilter(UserAgentFilter.java:83)
        at org.eclipse.jetty.servlets.GzipFilter.doFilter(GzipFilter.java:351)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1622)
        at com.zimbra.cs.servlet.ContextPathBasedThreadPoolBalancerFilter.doFilter(ContextPathBasedThreadPoolBalancerFilter.java:107)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1622)
        at com.zimbra.cs.servlet.ZimbraQoSFilter.doFilter(ZimbraQoSFilter.java:116)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1622)
        at org.eclipse.jetty.servlets.DoSFilter.doFilterChain(DoSFilter.java:457)
        at org.eclipse.jetty.servlets.DoSFilter.doFilter(DoSFilter.java:326)
        at org.eclipse.jetty.servlets.DoSFilter.doFilter(DoSFilter.java:299)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1622)
        at com.zimbra.webClient.filters.CharEncodingFilter.doFilter(CharEncodingFilter.java:37)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1622)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:549)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
        at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:544)
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:221)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1111)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:478)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:183)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1045)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
        at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:199)
        at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:109)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
        at org.eclipse.jetty.rewrite.handler.RewriteHandler.handle(RewriteHandler.java:309)
        at org.eclipse.jetty.server.handler.DebugHandler.handle(DebugHandler.java:81)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
        at org.eclipse.jetty.server.Server.handle(Server.java:462)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:279)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:232)
        at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:534)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:607)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:536)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: Unterminated quote
        at java.text.SimpleDateFormat.compile(SimpleDateFormat.java:842)
        at java.text.SimpleDateFormat.initialize(SimpleDateFormat.java:634)
        at java.text.SimpleDateFormat.<init>(SimpleDateFormat.java:605)
        at com.zimbra.cs.taglib.tag.i18n.FormatDateTag.doTag(FormatDateTag.java:91)
        at org.apache.jsp.tag.web.calendar.multiDay_tag._jspx_meth_fmt_formatDate_9(org.apache.jsp.tag.web.calendar.multiDay_tag:4511)
        at org.apache.jsp.tag.web.calendar.multiDay_tag.doTag(org.apache.jsp.tag.web.calendar.multiDay_tag:875)
        at org.apache.jsp.tag.web.calendar.multiDayPrintView_tag._jspx_meth_app_multiDay_0(org.apache.jsp.tag.web.calendar.multiDayPrintView_tag:335)
        at org.apache.jsp.tag.web.calendar.multiDayPrintView_tag._jspx_meth_c_set_1(org.apache.jsp.tag.web.calendar.multiDayPrintView_tag:300)
        at org.apache.jsp.tag.web.calendar.multiDayPrintView_tag.access$4(org.apache.jsp.tag.web.calendar.multiDayPrintView_tag:284)
        at org.apache.jsp.tag.web.calendar.multiDayPrintView_tag$multiDayPrintView_tagHelper.invoke0(org.apache.jsp.tag.web.calendar.multiDayPrintView_tag:439)
        at org.apache.jsp.tag.web.calendar.multiDayPrintView_tag$multiDayPrintView_tagHelper.invoke(org.apache.jsp.tag.web.calendar.multiDayPrintView_tag:455)
        at org.apache.jsp.tag.web.infra.handleError_tag._jspx_meth_c_catch_0(org.apache.jsp.tag.web.infra.handleError_tag:222)
        at org.apache.jsp.tag.web.infra.handleError_tag.doTag(org.apache.jsp.tag.web.infra.handleError_tag:86)
        ... 65 more
`

**Comment by adriangibanelbtactic** [comment]
Can you please specify:
- Which exact version of ZCS are you using?
- Which version / branch / tag of the zimbra-catala repository are you using?

Thank you.

**Comment by anton01** [comment]
Hello,

This is Zimbra 8.6 patch 6 with master branch downloaded "catalan-8.6_20-11-2015.tgz"

Thank you

**Comment by adriangibanelbtactic** [comment]
Can you describe step-by-step after logging into Zimbra how to achieve this:

"Cuando intento imprimir el calendario la hoja de impresión sale en blanco."

exactly?

So that we can reproduce the bug on our own?

Thank you.

**Comment by anton01** [comment]
Hello,
After to log in webmail should go to calendar tab.
In weekly view and work  weekly view, push print button.
The new window to print appear without appointments.

Thank you.

**Comment by anton01** [comment]
Hello the last release fix the issue.

Thank you very much.
